import TensorCore

#print axioms TensorCore.rawProduct_value
#print axioms TensorCore.sum_coefficients
#print axioms TensorCore.alignment_value
#print axioms TensorCore.alignment_residual
#print axioms TensorCore.terms_value
#print axioms TensorCore.accumulator_value
#print axioms TensorCore.block_residual_identity
#print axioms TensorCore.returned_residual_identity
#print axioms TensorCore.evalBlock_residual_identity
#print axioms TensorCore.corrected_eq_round_exactDot
#print axioms TensorCore.fold_residual_ledger
#print axioms TensorCore.encoded_trace_ledger
#print axioms TensorCore.runBlocks_chain
#print axioms TensorCore.runBlocks_residual_ledger
#print axioms TensorCore.Regression.r1_equal_product_values
#print axioms TensorCore.Regression.r1_factorization_changes_output
#print axioms TensorCore.Regression.r1a_trace
#print axioms TensorCore.Regression.r1b_trace
#print axioms TensorCore.Regression.r2_trace
#print axioms TensorCore.Regression.r2_correction_unchanged
#print axioms TensorCore.Regression.r3_trace
#print axioms TensorCore.Regression.r4_binade_asymmetry
#print axioms TensorCore.Regression.r4_midpoint_distances
#print axioms TensorCore.Regression.r4_cancellation
#print axioms TensorCore.Regression.r4_signed_truncation
#print axioms TensorCore.Regression.r4_even_tie
#print axioms TensorCore.Regression.r4_odd_tie
#print axioms TensorCore.Regression.r4_binade_carry
#print axioms TensorCore.Regression.r4_subnormal_boundary
#print axioms TensorCore.Regression.r4_zero_tie
#print axioms TensorCore.Regression.r4_negative_zero
#print axioms TensorCore.Regression.zero_block
#print axioms TensorCore.Regression.subnormal_multiplicand
#print axioms TensorCore.Regression.subnormal_accumulator
#print axioms TensorCore.Regression.nonfinite_rejected
#print axioms TensorCore.Regression.out_of_range_rejected
#print axioms TensorCore.Regression.wrong_shape_rejected
#print axioms TensorCore.Regression.v100_nonmonotonicity_witness
#print axioms TensorCore.Regression.two_block_cancellation
#print axioms TensorCore.Regression.two_block_corrected
#print axioms TensorCore.decode32_finite
#print axioms TensorCore.value32_finite
#print axioms TensorCore.encode32_toNat
#print axioms TensorCore.encode32_value
#print axioms TensorCore.encode32_quantum
#print axioms TensorCore.rneInt_nearest
#print axioms TensorCore.rneInt_tie_even
#print axioms TensorCore.magnitudeExponent_spec
#print axioms TensorCore.convExp_bounds
#print axioms TensorCore.convCoeff_bounds
#print axioms TensorCore.carry_spec
#print axioms TensorCore.round32_nonzero_spec
#print axioms TensorCore.round32_nearestEven_correct
#print axioms TensorCore.finalRound_correct
#print axioms TensorCore.output_residual_bound
#print axioms TensorCore.block_alignment_bound
#print axioms TensorCore.block_error_bound
#print axioms TensorCore.evalBlock_error_bound
#print axioms TensorCore.corrected_correct
#print axioms TensorCore.evalBlock_corrected_correct
#print axioms TensorCore.correctedSchedule_correct
#print axioms TensorCore.runBlocks_corrected_correct
#print axioms TensorCore.runBlocks_idealContributions
#print axioms TensorCore.Program.recovery
#print axioms TensorCore.Program.vc_sound
#print axioms TensorCore.runLocated_erases
#print axioms TensorCore.Program.report_accepts_iff
#print axioms TensorCore.runBlocks_append
#print axioms TensorCore.runBlocks_repeat_invariant
#print axioms TensorCore.Program.repeat_vc_of_cycle
#print axioms TensorCore.Regression.cancellation_program_inputs
#print axioms TensorCore.Regression.cancellation_program_correct
#print axioms TensorCore.Regression.cancellation_program_report
#print axioms TensorCore.Regression.repeated_program_correct
#print axioms TensorCore.Regression.repeated_program_report
#print axioms TensorCore.Regression.nested_program_order
#print axioms TensorCore.Regression.rejected_program_vc
#print axioms TensorCore.Regression.rejected_program_location
#print axioms TensorCore.Regression.final_range_rejected
#print axioms TensorCore.Regression.zero_iterations_correct
#print axioms TensorCore.Regression.nonfinite_initial_rejected
#print axioms TensorCore.Regression.symbolic_cycle_correct
#print axioms TensorCore.Regression.symbolic_syntax_inputs

#print axioms TensorCore.packedIEEE_decode
#print axioms TensorCore.padded_decode_requires_zero
#print axioms TensorCore.operand_decode_bounded
#print axioms TensorCore.roundBinary_fp32
#print axioms TensorCore.roundBinary_range
#print axioms TensorCore.conversionStage_output
#print axioms TensorCore.runConversions_recovery
#print axioms TensorCore.runConversions_events
#print axioms TensorCore.evalInvocation_spec
#print axioms TensorCore.evalInvocation_recovery
#print axioms TensorCore.evalInvocation_output
#print axioms TensorCore.legacy_invocation_bits
#print axioms TensorCore.v100_invocation_bits
#print axioms TensorCore.alignmentScale_none
#print axioms TensorCore.eta_term
#print axioms TensorCore.rawMul_bounded
#print axioms TensorCore.aligned_term_coefficient_bound
#print axioms TensorCore.prepare_terms_bounded
#print axioms TensorCore.machineAccumulate_eq
#print axioms TensorCore.machineAccumulate_exact
#print axioms TensorCore.machineAccumulate_prefix_exact
#print axioms TensorCore.coefficient_width_sufficient
#print axioms TensorCore.evalBlock_machineAccumulator
#print axioms TensorCore.evalV100_machineAccumulator
#print axioms TensorCore.fp16Fp32_invocation_compatible
#print axioms TensorCore.fp16Fp32_contract
#print axioms TensorCore.ampere_machineAccumulator
#print axioms TensorCore.hopper_machineAccumulator
#print axioms TensorCore.Regression.extra_alignment_bit_matters
#print axioms TensorCore.Regression.canonical_profile_results
#print axioms TensorCore.Regression.signed_capacity_prefix
#print axioms TensorCore.canonical_eta_floor_inactive
#print axioms TensorCore.prepare_fp16_terms_lower
#print axioms TensorCore.alignmentScale_lower
