import TensorCore

#print axioms TensorCore.rawProduct_value
#print axioms TensorCore.sum_coefficients
#print axioms TensorCore.alignment_value
#print axioms TensorCore.alignment_residual
#print axioms TensorCore.terms_value
#print axioms TensorCore.accumulator_value
#print axioms TensorCore.block_residual_identity
#print axioms TensorCore.returned_residual_identity
#print axioms TensorCore.evalBlock_residual_identity
#print axioms TensorCore.corrected_eq_round_exactDot
#print axioms TensorCore.fold_residual_ledger
#print axioms TensorCore.encoded_trace_ledger
#print axioms TensorCore.runBlocks_chain
#print axioms TensorCore.runBlocks_residual_ledger
#print axioms TensorCore.Regression.r1_equal_product_values
#print axioms TensorCore.Regression.r1_factorization_changes_output
#print axioms TensorCore.Regression.r1a_trace
#print axioms TensorCore.Regression.r1b_trace
#print axioms TensorCore.Regression.r2_trace
#print axioms TensorCore.Regression.r2_correction_unchanged
#print axioms TensorCore.Regression.r3_trace
#print axioms TensorCore.Regression.r4_binade_asymmetry
#print axioms TensorCore.Regression.r4_midpoint_distances
#print axioms TensorCore.Regression.r4_cancellation
#print axioms TensorCore.Regression.r4_signed_truncation
#print axioms TensorCore.Regression.r4_even_tie
#print axioms TensorCore.Regression.r4_odd_tie
#print axioms TensorCore.Regression.r4_binade_carry
#print axioms TensorCore.Regression.r4_subnormal_boundary
#print axioms TensorCore.Regression.r4_zero_tie
#print axioms TensorCore.Regression.r4_negative_zero
#print axioms TensorCore.Regression.zero_block
#print axioms TensorCore.Regression.subnormal_multiplicand
#print axioms TensorCore.Regression.subnormal_accumulator
#print axioms TensorCore.Regression.nonfinite_rejected
#print axioms TensorCore.Regression.out_of_range_rejected
#print axioms TensorCore.Regression.wrong_shape_rejected
#print axioms TensorCore.Regression.v100_nonmonotonicity_witness
#print axioms TensorCore.Regression.two_block_cancellation
