name = "tensorCore"
version = "0.1.0"
defaultTargets = ["TensorCore", "tc_trace", "tc_features"]

[[lean_lib]]
name = "TensorCore"

[[lean_exe]]
name = "tc_trace"
root = "Main"

[[lean_exe]]
name = "tc_features"
root = "FeatureMain"
