-- GEMM semantics, error bounds, and certificates.

import TensorCore.Gemm.Analysis
import TensorCore.Gemm.Bounds
import TensorCore.Gemm.Cli.Analysis
import TensorCore.Gemm.Cli.ExtendedAnalysis
import TensorCore.Gemm.Cli.Gemm
import TensorCore.Gemm.Cli.GemmInput
import TensorCore.Gemm.Cli.GemmSelection
import TensorCore.Gemm.Cli.NativePipeline
import TensorCore.Gemm.Cli.PipelineAnalysis
import TensorCore.Gemm.ConversionBounds
import TensorCore.Gemm.ConvertedGemmAnalysis
import TensorCore.Gemm.CostSelection
import TensorCore.Gemm.Defs
import TensorCore.Gemm.EntryFamily
import TensorCore.Gemm.ExactScalarAnalysis
import TensorCore.Gemm.Family
import TensorCore.Gemm.InputBounds
import TensorCore.Gemm.Kernels.CutlassWmma
import TensorCore.Gemm.Matrix
import TensorCore.Gemm.MatrixConversion
import TensorCore.Gemm.NativeConvertedAnalysis
import TensorCore.Gemm.NativeGemm
import TensorCore.Gemm.NativeScaledGemm
import TensorCore.Gemm.RoundingBudget
import TensorCore.Gemm.ScalarAnalysis
import TensorCore.Gemm.ScaledGemm
import TensorCore.Gemm.ScaledGemmAnalysis
import TensorCore.Gemm.ScaledGemmBounds
import TensorCore.Gemm.Selection
import TensorCore.Gemm.Specification.GemmComposition
import TensorCore.Gemm.Specification.GemmEquivalence
import TensorCore.Gemm.Specification.Matrix
import TensorCore.Gemm.Specification.NativeGemmEquivalence
import TensorCore.Gemm.Specification.NativeMatrix
import TensorCore.Gemm.Specification.NativeScaledGemmEquivalence
import TensorCore.Gemm.Specification.NativeScaledMatrix
import TensorCore.Gemm.Specification.Scalar
import TensorCore.Gemm.Specification.ScalarRounding
import TensorCore.Gemm.Specification.ScaledGemmEquivalence
import TensorCore.Gemm.TightBounds
import TensorCore.Gemm.TightInputBounds
